import Admin from "./Admin";
import CartPage from "./Cart";
import CheckoutPage from "./Checkout";
import HomePage from "./Home";
import OrdersPage from "./Order";
import ProductPage from "./ProductPage";
import ProfilePage from "./Profile";
import WishlistPage from "./wishlistPage";
import ArivalList from "./ArivalList";
export { ArivalList, Admin, CartPage, CheckoutPage, HomePage, OrdersPage, ProductPage, ProfilePage, WishlistPage };